spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://35.226.209.194/stsm
    username: postgres
    password: Warcraft3

server:
   port: 8080
   
eureka:
  client:
    serviceUrl:
      defaultZone: https://stsm-eureka.herokuapp.com/eureka #http://localhost:8761/eureka/
  instance:
    hostname: localhost
    nonSecurePort: 8080